export const availableActivities = [
    // --- AGRICULTURE, AGRO-ALIMENTAIRE & ÉLEVAGE ---
    "Agro-alimentaire", "Agro-pastoral", "Agriculture (Maraîchage / Vivriers)",
    "Élevage (Aviculture, Porciculture, Pisciculture)", "Transformation agro-alimentaire",
    "Production de jus et boissons locales", "Apiculture", "Vente d'intrants agricoles",
    "Pépinière et horticulture", "Transformation d'huile de palme",
    "Culture du cacao", "Culture du café", "Culture de la banane plantain",
    "Culture du manioc et tubercules", "Agroforesterie", "Cuniculture (Élevage de lapins)",
    "Élevage bovin / ovin / caprin", "Champignonnière", "Production de compost et engrais",
    "Ferme maraîchère biologique", "Séchage et conservation alimentaire",
    "Apiculture et produits dérivés", "Production de vin de palme",
    "Riziculture", "Maïsiculture", "Hévéaculture",

    // --- BEAUTÉ, ESTHÉTIQUE & COSMÉTIQUE ---
    "Esthétique et Onglerie", "Coiffure",
    "Maquillage artistique et de scène", "Maquillage permanent (Dermopigmentation)",
    "Microblading et rehaussement de sourcils", "Extensions de cils (Pose de faux cils)",
    "Soins du visage (Soins esthétiques)", "Soins corporels et enveloppements",
    "Soins anti-âge et rajeunissement", "Traitement de l'acné et des imperfections",
    "Peeling chimique et exfoliation", "Épilation au fil", "Épilation à la cire",
    "Épilation laser et lumière pulsée", "Épilation électrique",
    "Nail art et décoration ongles", "Pose d'ongles (Gel, Acrylique, Polygel)",
    "Manucure et Pédicure",
    "Tressage africain et nattes", "Extensions capillaires",
    "Lissage brésilien / Kératine", "Traitement capillaire spécialisé",
    "Pose de perruques et tissages",
    "Bronzage UV / Autobronzant", "Cryothérapie esthétique",
    "Soins amincissants et raffermissants", "Drainage lymphatique manuel",
    "Massage esthétique (anti-cellulite, modelage)", "Massage relaxant et bien-être",
    "Tatouage", "Piercing",
    "Soins naturels et cosmétiques bio", "Fabrication de cosmétiques artisanaux",
    "Vente de cosmétiques et produits de beauté", "Vente de produits capillaires",
    "Institut de beauté", "Spa et soins du corps",
    "Coaching beauté et relooking", "Conseil en image et colorimétrie",
    "Formation en esthétique et maquillage",

    // --- CONSTRUCTION, BTP & IMMOBILIER ---
    "Construction et immobilier", "Maçonnerie", "Plomberie", "Électricité bâtiment",
    "Menuiserie (Bois/Alu/Métal)", "Peinture et décoration intérieure", "Architecture",
    "Vente de matériaux de construction", "Fabrication de parpaings", "Serrurerie", "Géomètre-expert",
    "Carrelage", "Étanchéité", "Promotion immobilière", "Gestion locative",
    "Location d'engins de chantier", "Rénovation et réhabilitation", "Construction métallique",
    "Isolation thermique et phonique", "Aménagement paysager", "Construction écologique",
    "Démolition et désamiantage", "Topographie et levés géodésiques", "Construction modulaire",
    "Couverture et charpente", "Pose de vitrages et menuiserie PVC",
    "Climatisation et ventilation (CVC)", "Domotique et maison connectée",
    "Installation de cuisine équipée", "Électricité solaire et réseau photovoltaïque",
    "Terrassement et voirie", "Forage de puits et fondations",

    // --- TECHNOLOGIE, DIGITAL & SERVICES B2B ---
    "Informatique et services numériques", "Développement Web et Mobile", "Graphisme et Design",
    "Rédaction Web et Copywriting", "Référencement (SEO/SEA)", "Cybersécurité",
    "Data Analysis et Business Intelligence", "Installation réseau et fibre",
    "Réparation informatique et téléphones", "Vente de matériel informatique",
    "Marketing digital", "Conseil en stratégie", "Comptabilité et Expertise comptable",
    "Secrétariat externalisé", "RH et Recrutement", "Assistance juridique",
    "Traduction et Interprétariat", "Nettoyage industriel", "Sécurité et Gardiennage",
    "Impression et reprographie", "Community Management",
    "Services aux entreprises", "Consulting et formation professionnelle",
    "Développement de logiciels sur mesure", "Gestion de projet IT",
    "Infogérance et maintenance informatique", "Intelligence artificielle et automatisation",
    "Production de podcasts et contenus audio", "Montage vidéo et motion design",
    "UX/UI Design", "E-learning et formation en ligne",
    "Gestion de réseaux sociaux", "Publicité en ligne (Facebook Ads, Google Ads)",
    "Création de contenu (YouTubeur, Influenceur)", "Streaming et production audiovisuelle",

    // --- COMMERCE & DISTRIBUTION ---
    "Commerce de détail", "Supermarché / Épicerie", "Friperie",
    "Vente de vêtements et accessoires", "Vente d'électroménager",
    "Vente de produits pharmaceutiques", "Quincaillerie",
    "Vente de meubles et literie", "Vente de produits électroniques / téléphonie",
    "Vente en ligne / E-commerce", "Grossiste alimentaire",
    "Librairie / Papeterie", "Vente de matériel médical et paramédical",
    "Herboristerie et médecine par les plantes", "Vente de semences et intrants agricoles",
    "Droguerie / Bazar", "Vente de bijoux et montres",
    "Vente d'articles de sport", "Vente de jouets et articles enfants",
    "Vente de matériel de bureau", "Vente de produits culturels (livres, musique, films)",
    "Solderie / Discount", "Vente de produits alimentaires locaux (mil, farine, épices)",
    "Vente de pagnes et tissus africains", "Import-export",

    // --- SANTÉ, MÉDECINE & PARAMÉDICAL ---
    "Clinique médicale / Cabinet médical", "Clinique dentaire / Dentiste",
    "Laboratoire d'analyses médicales", "Pharmacie", "Optique et opticien",
    "Kinésithérapie / Physiothérapie", "Orthophonie",
    "Sage-femme / Cabinet de maternité", "Infirmier(e) à domicile",
    "Soins infirmiers spécialisés", "Médecine traditionnelle et phytothérapie",
    "Médecine douce (Naturopathie, Ayurveda)", "Ostéopathie",
    "Acupuncture", "Audiologie et prothèses auditives",
    "Orthopédie et appareillage", "Radiologie et imagerie médicale",
    "Psychologie clinique", "Psychiatrie",
    "Diététique et Nutrition", "Médecine sportive",
    "Soins palliatifs et accompagnement", "Ambulance et transport sanitaire",

    // --- BIEN-ÊTRE, SPORT & COACHING ---
    "Massage et Spa", "Coaching Sportif", "Salle de sport / Fitness",
    "Yoga et méditation", "Pilates",
    "Arts martiaux (Judo, Karaté, MMA, Taekwondo)", "Danse (Africaine, Moderne, Classique)",
    "Natation et aquagym", "CrossFit et entraînement fonctionnel",
    "Coaching de vie (Life coaching)", "Développement personnel",
    "Retraite bien-être et séjour détox", "Hammam et bain de vapeur",
    "Thérapie par le son et la relaxation",

    // --- ÉDUCATION, FORMATION & PETITE ENFANCE ---
    "Cours d'appui / Soutien scolaire", "Établissement d'enseignement privé",
    "Centre de formation professionnelle", "Formation en langues étrangères",
    "Crèche et garderie", "École maternelle privée",
    "Centre de loisirs pour enfants", "Activités périscolaires",
    "Formation en couture et mode", "Formation en cuisine et pâtisserie",
    "Formation en informatique", "Formation en management et leadership",
    "Cours de musique", "Cours de dessin et peinture",
    "Formation en sécurité et premiers secours",

    // --- TRANSPORT, LOGISTIQUE & ÉNERGIE ---
    "Transport (Taxi / VTC)", "Transport (Moto-taxi)", "Location de véhicules",
    "Logistique et Transit", "Livraison à domicile (Coursier)",
    "Auto-école", "Transport scolaire", "Transport de marchandises",
    "Lavage auto et entretien véhicules", "Mécanique auto/moto",
    "Installation solaire et panneaux photovoltaïques",
    "Vente de gaz domestique", "Station-service / Pompe à carburant",
    "Dépannage et remorquage", "Électricité automobile",
    "Location de motos et vélos", "Transport fluvial",
    "Gestion de flotte et affrètement", "Déménagement",

    // --- ALIMENTATION, RESTAURATION & BOISSONS ---
    "Restauration (Restaurant)", "Fast-food / Street food",
    "Bar / Lounge / Buvette", "Traiteur (Catering)",
    "Boulangerie / Pâtisserie", "Chocolaterie et confiserie",
    "Vente de glaces et sorbets", "Coffee shop / Salon de thé",
    "Cuisine africaine traditionnelle (traiteur)", "Production de yaourt artisanal",
    "Production de fromage", "Brasserie artisanale",
    "Production de boissons fermentées (kefir, kombucha, gingembre)",
    "Épicerie fine et produits du terroir", "Vente de fruits et légumes frais",
    "Snack et sandwicherie", "Food truck",

    // --- ÉVÉNEMENTIEL, CRÉATION & TOURISME ---
    "Photographie et Vidéographie", "Organisation de mariages / Événements",
    "Décoration événementielle", "Fleuriste",
    "Hôtellerie", "Maison d'hôtes / Airbnb",
    "Agence de tourisme et voyages", "Guide touristique",
    "Animation DJ / Sound system", "Artiste musicien",
    "Artiste plasticien / Peintre",
    "Création de contenu artistique", "Studio d'enregistrement",
    "Location de matériel événementiel", "Sécurité événementielle",
    "Maître de cérémonie (MC)", "Agence de communication et relations publiques",
    "Organisation de séminaires et conférences",

    // --- ARTISANAT & MÉTIERS MANUELS ---
    "Couture et Stylisme", "Broderie et dentelle",
    "Tissage traditionnel (Kente, Ndop, etc.)", "Teinture (Indigo, tie-dye)",
    "Vannerie et osier", "Poterie et céramique",
    "Sculpture sur bois et sur pierre", "Bijouterie artisanale",
    "Maroquinerie (sacs, ceintures, chaussures cuir)", "Cordonnerie",
    "Ébénisterie et mobilier artisanal", "Ferronnerie d'art",
    "Sérigraphie et impression textile", "Reliure et papeterie créative",
    "Fabrication de savons et cosmétiques artisanaux",
    "Fabrication de bougies et parfums", "Lutherie (fabrication instruments)",

    // --- IMMOBILIER & SERVICES À DOMICILE ---
    "Agent immobilier", "Gestionnaire de biens locatifs",
    "Nettoyage / Ménage à domicile", "Garde d'enfants à domicile",
    "Aide à domicile pour personnes âgées", "Garde d'animaux / Pet-sitting",
    "Jardinage et entretien d'espaces verts", "Lavage de vitres",
    "Réparations et bricolage à domicile", "Débarras et nettoyage de fin de chantier",
    "Pressing et blanchisserie", "Couture et retouches à domicile",
    "Livraison de repas à domicile", "Conciergerie privée",

    // --- JURIDIQUE, FINANCE & ASSURANCE ---
    "Avocat / Cabinet d'avocats", "Notaire",
    "Huissier de justice", "Expert-comptable",
    "Conseiller financier", "Agent d'assurance",
    "Courtier en crédit", "Cabinet de recouvrement",
    "Assistance à la création d'entreprise",
    "Conseil fiscal et optimisation", "Audit et contrôle de gestion",
    "Microfinance et tontine formelle",

    // --- TERMES GÉNÉRALISTES (couvrent plusieurs branches) ---
    "Informatique", "Numérique", "Technologie",
    "Commerce", "Vente", "Distribution",
    "Agriculture", "Élevage", "Agroalimentaire",
    "Construction", "BTP", "Immobilier",
    "Santé", "Médecine", "Paramédical",
    "Beauté", "Esthétique", "Cosmétique", "Coiffure",
    "Éducation", "Formation", "Enseignement",
    "Transport", "Logistique", "Mobilité",
    "Énergie", "Environnement",
    "Finance", "Comptabilité", "Assurance", "Banque",
    "Juridique", "Droit",
    "Communication", "Marketing", "Publicité",
    "Médias", "Audiovisuel", "Création",
    "Artisanat", "Métiers manuels",
    "Restauration", "Alimentation", "Boissons",
    "Tourisme", "Hôtellerie", "Loisirs",
    "Sport", "Bien-être",
    "Événementiel", "Animation",
    "Sécurité", "Surveillance",
    "Services à domicile", "Aide à la personne",
    "Art", "Culture",
    "Mode", "Textile",
    "Industrie", "Production", "Fabrication",
    "Nettoyage", "Hygiène",
    "Conseil", "Consulting",
    "Ressources humaines",
    "Design", "Architecture",

    // --- AUTRES ---
    "Autres"
];
